services:
  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_DB: "ApplyInnopolis"
      POSTGRES_USER: "applyinnopolisapi"
      POSTGRES_PASSWORD: "e7Y8F0H9sa3cdvMcBGvW"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - apply-innopolis-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  frontend:
      build: ./Frontend
      network_mode: host
  backend:
      build: ./Backend
      network_mode: host

volumes:
  apply-innopolis-db-data:
